version: '3'

services:
  web:
    image: rpdelavirgen/finalsphp
    container_name: php
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app
    ports:
       - "8000:80"
    stdin_open: true
    tty: true




  db:
    image: rpdelavirgen/finalsdb
    container_name: mboardloginDB
    ports:
      - "3306:3306"

